### ISSUE TITLE
Auth refreshing repeatedly

### ISSUE THREAD

**Issue by Zoramite** [grow/grow-ext-kintaro#10]
Currently when attempting to sync with kintaro, each time it tries to sync a collection it is showing this:

    Attempting refresh to obtain initial access_token
    Refreshing access_token

The token should only need to be refreshed once.

**Comment by jeremydw** [comment]
This can be fixed by using one service and passing the service in when the extension is run. I wrote the code for this but unfortunately I think I reverted it in my local workspace.

**Comment by jeremydw** [comment]
Should add a `service` parameter in to `download_entries` and `download_entry` -> https://github.com/grow/grow-ext-kintaro/blob/master/kintaro/kintaro.py#L261

And pass it down through where necessary.
