### ISSUE TITLE
Missing documents causes failure in import

### ISSUE THREAD

**Issue by juan-insuasti** [grow/grow-ext-kintaro#27]
After upgrading to grow 0.8.22 we found that there is an error when extension tries to download new documents.  

```
grow.pods.errors.DocumentDoesNotExistError: Referenced document does not exist: /content/Components/Cards/5407287246848000.yaml
[47748] Failed to execute script grow
```
Our current workaround is to create an empty file but this is a lot of trouble when multiple team members are creating new documents.

**Comment by Zoramite** [comment]
This is basically caused by dependency issues with how the kintaro collections are imported. The thing we need to fix is how the extension reacts when there isn't a document but it wants to reference one.
